
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'dataplatform'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'dataplatform_local'

# Paths configuration
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
packages-install-path: dbt_packages


target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"


# Models configuration
models:
  dataplatform:
    stg:
      +database: "stg"
      # indice_des_prix:
        # +group: "indice_des_prix"
        # +schema: "indice_des_prix"
    ods:
      +database: "ods"
      # indice_des_prix:
        # +group: "indice_des_prix"
        # +schema: "indice_des_prix"
