
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'annuaire_statistique'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'dataplatform_local'

# Paths configuration
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
packages-install-path: dbt_packages


target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"


# Models configuration
models:
  annuaire_statistique:
    stg:
      +database: "stg"
    ods:
      +database: "ods"
