dataplatform_local:
  target: prod
  outputs:
    prod:
      type: duckdb
      path: "{{ env_var('DUCKDB_DATA') }}/raw.duckdb"
      database: raw
      extensions:
        - httpfs
        - parquet
      attach:
        - path: "{{ env_var('DUCKDB_DATA') }}/stg.duckdb"
          alias: "stg"
        - path: "{{ env_var('DUCKDB_DATA') }}/int.duckdb"
          alias: "int"
        - path: "{{ env_var('DUCKDB_DATA') }}/ods.duckdb"
          alias: "ods"