dataplatform_local:
  target: prod
  outputs:
    prod:
      type: duckdb
      path: "{{ env_var('DUCKDB_DATA') }}/dbt.duckdb"
      database: dbt
      extensions:
        - httpfs
        - parquet
      attach:
        - path: "{{ env_var('DUCKDB_DATA') }}/stg_duck.db"
          alias: "stg"
        - path: "{{ env_var('DUCKDB_DATA') }}/ods_duck.db"
          alias: "ods"
        # - path: "{{ env_var('DUCKDB_DATA') }}/raw_duck.db"
        #   alias: raw
        #   read_only: true
          