sources:
  - name: indice_des_prix
    meta:
      external_location: "{{ env_var('DWH_DATA') }}/raw/indice_des_prix/{name}.parquet"
    tables:
      - name: ipp_v1
        description: "Industrial, energy and mining producer price index"
        columns:
          - name: libelle_fr
            description: "French label"
            tests:
              - unique
              - not_null
          - name: libelle_ar
            description: "Arabic label"
            tests:
              - unique
              - not_null
          - name: '2019'
            description: "Value for year 2019"
            tests:
              - not_null
          - name: '2018'
            description: "Value for year 2018"
            tests:
              - not_null
          - name: '2017'
            description: "Value for year 2017"
            tests:
              - not_null
          - name: '2016'
            description: "Value for year 2016"
            tests:
              - not_null