name: '[CD] Deploy Data Catalog'

on:
  workflow_dispatch:

  pull_request: 
    types:
      - closed
    branches:
      - main
    paths:
    - 'lab/dbt/dataplatform/**.yml'
    - 'lab/dbt/dataplatform/**.md'


jobs:
  deploy:
    name: 'Deploy Data Catalog'
    runs-on: ubuntu-latest
    env:
      DBT_PROJECT_DIR: ${{ github.workspace }}/lab/dbt/dataplatform
      DBT_PROFILES_DIR: ${{ github.workspace }}/lab/dbt/profiles
      DBT_TARGET_PATH: ${{ github.workspace }}/lab/dbt/dataplatform/target
      DUCKDB_DATA: ${{ github.workspace }}/lab/duckdb_data
      DWH_DATA: ${{ github.workspace }}/lab/dwh_data
    steps:
    - name: 'Checkout branch'
      uses: 'actions/checkout@v2'

    - name: 'Setup Python 3.10'
      uses: actions/setup-python@v2
      with:
        python-version: 3.10

    - name: 'Cache virtualenv'
      uses: syphar/restore-virtualenv@v1
      id: cache-virtualenv
      with:
        requirement_files: ${{ github.workspace }}/requirements.txt 

    - name: 'Restore cache'
      uses: syphar/restore-pip-download-cache@v1
      if: steps.cache-virtualenv.outputs.cache-hit != 'true'

    - name: 'Install dependencies'
      if: steps.cache-virtualenv.outputs.cache-hit != 'true'
      run: |
        pip install -r requirements.txt
    
    - name: 'Test database connection'
      run: dbt debug

    - name: 'Install dbt packages'
      run: dbt deps

    - name: 'Generate & Deploy Data Catalog'
      run: dbt docs generate
      
    - name: 'Upload GitHub Pages artifact'
      uses: actions/upload-pages-artifact@v1.0.8
      with:
        path: ${{ env.DBT_TARGET_PATH }}
        
    - name: 'Deploy GitHub Pages site'
      uses: actions/deploy-pages@v2.0.1
